<section class="grid_12 basic">
    <header><h1>Tréninky</h1></header>

    {if !empty($trainings)}
    {foreach $training in $trainings}
    <div class="grid_12 trainingWrapper">
        <div class="trainingCalIcon">
            <img src="/public/images/icons/calendar.png" alt="" />
        </div>
        <div>
            <h2>{echo $training->title} - {echo date("d.m. Y", strtotime($training->startDate))}</h2>
            <div class="trainingControls">
                <a class="button-orange" href="/trenink/dochazka/{echo $training->id}/1">Přijdu</a>
                <a class="button-orange" href="/trenink/dochazka/{echo $training->id}/2">Nepřijdu</a>
                <a class="button-orange" href="/trenink/dochazka/{echo $training->id}/3">Možná</a>
            </div>
            
            {script $ucast = $neucast = $nevi=array();$countU = $countN = $countM=0}
            {script $attd = $training->getAttendance()}
            
            {if $attd !== null}
                {foreach $att in $attd}
                    {if $att->getStatus() ==1}
                        {script $ucast[] = $att->firstname." ".$att->lastname; $countU++}
                    {/if}
                    {elseif $att->getStatus() == 2}
                        {script $neucast[] = $att->firstname." ".$att->lastname; $countN++}
                    {/elseif}
                    {elseif $att->getStatus() == 3}
                        {script $nevi[] = $att->firstname." ".$att->lastname; $countM++}
                    {/elseif}
                {/foreach}
            {/if}

            <div class="trainingResult">
                <div>
                    Přijde ({echo $countU}):  {echo join(", ", $ucast)}
                </div>
                <div>
                    Nepřijde ({echo $countN}):  {echo join(", ", $neucast)}
                </div>
                <div>
                    Možná ({echo $countM}):  {echo join(", ", $nevi)}
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    {/foreach}
    {/if}
    {else}
    Hala je do odvolání zavřená
    {/else}
</section>
