<section class="grid_12 basic">
    <header><h1>Tréninky</h1></header>

    {if !empty($trainings)}
    {foreach $training in $trainings}
    <div class="grid_12 trainingWrapper">
        <div class="trainingCalIcon">
            <img src="/public/images/icons/calendar.png" alt="" />
        </div>
        <div>
            <h2>{echo $training->title} - {echo date("d.m. Y", strtotime($training->startDate))}</h2>
            <div class="trainingControls">
                <a class="button-orange" href="/trenink/dochazka/{echo $training->id}/1">Přijdu</a>
                <a class="button-orange" href="/trenink/dochazka/{echo $training->id}/2">Nepřijdu</a>
                <a class="button-orange" href="/trenink/dochazka/{echo $training->id}/3">Možná</a>
            </div>
            
            {script $ucast = $neucast = $nevi=array();$countU = $countN = $countM=0}

            {foreach $attd in $training->attendance}
            {if $attd["status"]==1}
                {script $ucast[] = $attd["firstname"]." ".$attd["lastname"]; $countU++}
            {/if}
            {elseif $attd["status"] == 2}
                {script $neucast[] = $attd["firstname"]." ".$attd["lastname"]; $countN++}
            {/elseif}
            {elseif $attd["status"] == 3}
                {script $nevi[] = $attd["firstname"]." ".$attd["lastname"]; $countM++}
            {/elseif}
            {/foreach}

            <div class="trainingResult">
                <div>
                    Přijde ({echo $countU}):  {echo implode(", ", $ucast)}
                </div>
                <div>
                    Nepřijde ({echo $countN}):  {echo implode(", ", $neucast)}
                </div>
                <div>
                    Možná ({echo $countM}):  {echo implode(", ", $nevi)}
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    {/foreach}
    {/if}
    {else}
    Hala je do odvolání zavřená
    {/else}
</section>
