<ul>
    <li class="current"><a href="/admin/" class="dashboard"><span>Dashboard</span></a></li>
    <li><a href="/admin/news/" class="editor"><span>News</span></a></li>
    <li><a href="/admin/match/" class="calendar"><span>Match</span></a></li>
    <li><a href="/admin/training/" class="calendar"><span>Training</span></a></li>
    <li><a href="/admin/sponsor/" class="contacts"><span>Sponsor</span></a></li>
    <li><a href="/admin/gallery/" class="media"><span>Gallery</span></a></li>
    <li><a href="/admin/video/" class="media"><span>Videos</span></a></li>
    <li><a href="/admin/chat/" class="chat"><span>Chat topics</span></a></li>
    {if $isSuperAdmin}
    <li><a href="/admin/analytics/" class="charts"><span>Analytics</span></a></li>
    <li><a href="/admin/user/" class="users"><span>Users</span></a></li>
    <li><a href="/admin/system/" class="error"><span>System</span></a></li>
    {/if}
    {elseif $isAdmin}
    <li><a href="/admin/user/" class="users"><span>Users</span></a></li>
    {/elseif}
</ul>