<section class="grid_12 basic">
    <header><h1>{echo $gallery->title}</h1></header>
    <div>
        {echo nl2br($gallery->description)}
    </div>
    <br/><br/>
    <div class="galleria">
        {if !empty($photos)}
        {foreach $photo in $photos}
        <a href="{echo $photo->pathLarge}">
            <img src="{echo $photo->pathSmall}" data-big="{echo $photo->pathLarge}" data-title="{echo $photo->photoName}" />
        </a>
        {/foreach}
        {/if}
    </div>
</section>

<script type="text/javascript" src="/public/js/galleria/galleria-1.3.3.min.js"></script>
<script type="text/javascript" src="/public/js/galleria-init.js"></script>