<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Match</a></li>
    <li><a href="/admin/match/add/">Add Match</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Match list</span></h2>
    </div><!--contenttitle-->

    <form method="post" class="massActionForm" action="/admin/match/massaction/">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
            <colgroup>
                <col class="con1" /> <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
                <col class="con0" />
            </colgroup>
            <thead>
                <tr>
                    <td class="head1 width50"><input type="checkbox" class="checkall" /></td>
                    <th class="head0">Home</th>
                    <th class="head1">Away</th>
                    <th class="head0">Date</th>
                    <th class="head1">Hall</th>
                    <th class="head0">Team</th>
                    <th class="head1">Score Home</th>
                    <th class="head0">Score Away</th>
                    <th class="head1">Status</th>
                    <th class="head0">&nbsp;</th>
                </tr> 
            </thead>

            <tbody>
                {if !empty($matches)}
                    {foreach $match in $matches}
                        <tr>
                            <td class="center">
                                <input type="checkbox" name="matchids[]" value="{echo $match->getId()}" />
                            </td>
                            <td>{echo $match->getHome()}</td>
                            <td>{echo $match->getAway()}</td>
                            <td>{echo $match->getStartDate()." ".$match->getStartTime()}</td>
                            <td>{echo $match->getHall()}</td>
                            <td>{echo strtoupper($match->getTeam())}</td>
                            <td>{echo $match->getScoreHome()}</td>
                            <td>{echo $match->getScoreAway()}</td>
                            <td>
                                {if ($match->active)}<span class="labelProduct labelProductGreen">Active</span>{/if}
                            </td>
                            <td>
                                <a href="/admin/match/edit/{echo $match->id}" class="btn btn3 btn_pencil" title="Edit"></a>
                                <a href="/admin/match/delete/{echo $match->id}" class="btn btn3 btn_trash ajaxBtn" title="Delete"></a>
                            </td>
                        </tr>
                    {/foreach}
                {/if}
            </tbody>
        </table>
        {if $isAdmin}
        <div class="tableoptions">
            Selected:
            <select class="radius3" name="action">
                <option value="activate">Activate</option>
                <option value="deactivate">Deactivate</option>
                <option value="delete">Delete</option>
            </select> &nbsp;
            <input class="radius3" type="submit" name="performMatchAction" value="Execute"/>
        </div><!--tableoptions-->
        {/if}
    </form>
</div>