<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Chat topics</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="image"><span>Chat topics</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="tk" id="tk" value="{echo $token}" />
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
        <colgroup>
            <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <td class="head1">Title</td>
                <td class="head0">Created by</td>
                <td class="head1">Created</td>
                <td class="head0">Status</td>
                <td class="head1">&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            {if !empty($topics)}
                {foreach $topic in $topics}
                    <tr>
                        <td>{echo $topic->getTitle()}</td>
                        <td>{echo $topic->getCreatedBy()}</td>
                        <td>{echo $topic->getCreated()}</td>
                        <td>
                            {if ($topic->active)}<span class="labelProduct labelProductGreen">Active</span>{/if}
                        </td>
                        <td>
                            {if $isAdmin}<a href="/admin/chat/delete/{echo $topic->getId()}" class="btn btn3 btn_trash deleteRow" title="Delete"></a>{/if}
                        </td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>