<section class="grid_12 basic">
    <header><h1>Kecárna</h1></header>
    <div>
        <form method="post" action="#" class="stdform">
            <p>
                <label>Vytvořit nové téma</label>
                <span class="field">
                    <input type="text" name="title" class="mediuminput" value="{echo isset($topic)? $topic->getTitle(): ""}"/>
                    <input type="submit" name="submitAddTopic" value="Vytvořit" />
                </span>
            </p>
    </div>
    <table>
        <tr>
            <td>Téma</td><td>Vytvořil</td>
            <td>Vytvořeno</td><td>Stav</td>
        </tr>

        {foreach $topic in $topics}
        <tr>
            <td>
                {if $topic->status == 0}{echo $topic->title}{/if}
                {else}<a href="/kecarna/{echo $topic->urlKey}">{echo $topic->title}</a>{/else}
            </td>
            <td>{echo $topic->firstname." ".$topic->lastname}</td>
            <td>{echo $topic->created}</td>
            <td>
                {if $topic->status == 0}Čeká na schválení{/if}
                {else}Tady to žije{/else}
            </td>
        </tr>
        {/foreach}
    </table>
</section>