<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/training/">Training</a></li>
    <li><a href="/admin/training/add/">Add Training</a></li>
    <li class="current"><a href="#">Edit Training</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Edit training</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />

        <p>
            <label>Title*</label>
            <span class="field">
                <input required type="text" name="title" class="longinput" 
                       value="{echo $training->title}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Location*</label>
            <span class="field">
                <input required type="text" name="location" class="longinput" 
                       value="{echo $training->location}" />
                {if isset($errors["location"])}
                <label class="error">{echo join("<br/>", $errors["location"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Date*</label>
            <span class="field">
                <input required type="text" name="date" class="longinput datepicker" 
                       value="{echo $training->startDate}" />
                {if isset($errors["startDate"])}
                <label class="error">{echo join("<br/>", $errors["startDate"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Time*</label>
            <span class="field">
                <input required type="time" name="time" class="longinput" 
                       value="{echo $training->startTime}" />
                {if isset($errors["startTime"])}
                <label class="error">{echo join("<br/>", $errors["startTime"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $training->active}
                        <option value="0">Inactive</option>
                        <option value="1" selected>Active</option>
                    {/if}
                    {else}
                        <option value="0" selected>Inactive</option>
                        <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>
                
        <p class="stdformbutton">
            <input name="submitEditTraining" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
