<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Training</a></li>
    <li><a href="/admin/training/add/">Add Training</a></li>
    <li><a href="/admin/training/attendance/">Training Attendance</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Training list</span></h2>
    </div><!--contenttitle-->

    <form method="post" class="massActionForm" action="/admin/training/massaction/">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
            <colgroup>
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
                <col class="con0" />
            </colgroup>
            <thead>
                <tr>
                    <td class="head0 width50"><input type="checkbox" class="checkall" /></td>
                    <th class="head1">Title</th>
                    <th class="head0">Location</th>
                    <th class="head1">Date</th>
                    <th class="head0">Time</th>
                    <th class="head1">Status</th>
                    <th class="head0">&nbsp;</th>
                </tr> 
            </thead>

            <tbody>
                {if !empty($trainings)}
                    {foreach $training in $trainings}
                        <tr>
                            <td class="center">
                                <input type="checkbox" name="trainingids[]" value="{echo $training->getId()}" />
                            </td>
                            <td>{echo $training->getTitle()}</td>
                            <td>{echo $training->getLocation()}</td>
                            <td>{echo $training->getStartDate()}</td>
                            <td>{echo $training->getStartTime()}</td>
                            <td>
                                {if ($training->active)}<span class="labelProduct labelProductGreen">Active</span>{/if}
                            </td>
                            <td>
                                <a href="/admin/training/detail/{echo $training->id}" class="btn btn3 btn_search" title="Detail"></a>
                                <a href="/admin/training/edit/{echo $training->id}" class="btn btn3 btn_pencil" title="Edit"></a>
                                <a href="/admin/training/delete/{echo $training->id}" class="btn btn3 btn_trash ajaxBtn" title="Delete"></a>
                            </td>
                        </tr>
                    {/foreach}
                {/if}
            </tbody>
        </table>
        {if $isAdmin}
        <div class="tableoptions">
            Selected:
            <select class="radius3" name="action">
                <option value="activate">Activate</option>
                <option value="deactivate">Deactivate</option>
                <option value="delete">Delete</option>
            </select> &nbsp;
            <input class="radius3" type="submit" name="performTrainingAction" value="Execute"/>
        </div><!--tableoptions-->
        {/if}
    </form>
</div>