<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/gallery/">Gallery</a></li>
    <li><a href="/admin/gallery/add/">Add Gallery</a></li>
    <li><a href="/admin/gallery/detail/{echo $gallery->id}">Gallery detail</a></li>
    <li class="current"><a href="#">Edit Gallery</a></li>
    {if $isAdmin}<li><a href="/admin/gallery/delete/{echo $gallery->id}">Delete Gallery</a></li>{/if}
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Edit Gallery</span></h2>
    </div><!--contenttitle-->
    
    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        
        <p>
            <label>Title*</label>
            <span class="field">
                <input class="longinput" type="text" name="title" value="{echo $gallery->title}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Public/Private</label>
            <span class="field">
                <select class="longinput" name="active">
                    {if $gallery->isPublic == 0}
                    <option value="0" selected>Private</option>
                    <option value="1">Public</option>
                    {/if}{else}
                    <option value="0">Private</option>
                    <option value="1" selected>Public</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Avatar</label>
            <span class="field">
                <select class="longinput" name="avatar">
                    {script $photos = $gallery->getPhotos()}
                    {if !empty($photos)}
                        {foreach $photo in $photos}
                            {if $photo->getId() == $gallery->getAvatarPhotoId()}
                                <option value="{echo $photo->getId()}" selected>{echo $photo->getPhotoName()}</option>
                            {/if}{else}
                                <option value="{echo $photo->getId()}">{echo $photo->getPhotoName()}</option>
                            {/else}
                        {/foreach}
                    {/if}
                </select>
            </span>
        </p>
        <p>
            <label>Description*<small>Max. 30 000 chars</small></label>
            <span class="field">
                <textarea class="longinput" name="description" id="ckeditor">{echo $gallery->description}</textarea>
                {if isset($errors["description"])}
                <label class="error">{echo join("<br/>", $errors["description"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select class="longinput" name="active">
                    {if $gallery->active == 0}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/if}{else}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/else}
                </select>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitEditGallery" type="submit" value="Save" class="submit radius2" />
        </p>
    </form>
</div>