<ul class="maintabmenu multipletabmenu">
    <li ><a href="/admin/sponsor/">All Sponsors</a></li>
    <li class="current"><a href="#">Add Sponsor</a></li>
</ul>

<div class="content">
    <div class="contenttitle">
        <h2 class="form"><span>Sponsor Informations</span></h2>
    </div>
    
    <form class="stdform stdform2" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>
        
        <p>
            <label>Sponsor name*</label>
            <span class="field">
                <input type="text" required name="title" class="longinput" 
                       value="{echo isset($sponsor)? $sponsor->title: ""}"/>
                {if isset($errors["title"])}
                    <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Logo*</label>
            <span class="field">
                <input type="file" name="logo" />
                {if isset($errors["logo"])}
                    <label class="error">{echo join("<br/>", $errors["logo"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Webpage*</label>
            <span class="field">
                <input type="url" required name="web" class="longinput" 
                       value="{echo isset($sponsor)? $sponsor->web: ""}"/>
                {if isset($errors["web"])}
                    <label class="error">{echo join("<br/>", $errors["web"])}</label>
                {/if}
            </span>
        </p>

        <p class="stdformbutton">
            <input name="submitAddSponsor" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
<br class="clear-all" />