<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/sponsor/">All Sponsors</a></li>
    <li><a href="/admin/sponsor/add/">Add Sponsor</a></li>
    <li class="current"><a href="#">Edit Sponsor</a></li>
</ul>

<div class="content">
    <div class="contenttitle">
        <h2 class="form"><span>Sponsor Informations</span></h2>
    </div>
    
    <form class="stdform stdform2" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>

        <p>
            <label>Sponsor name*</label>
            <span class="field">
                <input required type="text" name="title" class="longinput" value="{echo $sponsor->title}"/>
                {if isset($errors["title"])}
                    <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Logo*</label>
            {if $sponsor->logo != ""}
            <span class="field" id="currentLogo">
                <img src="{echo $sponsor->logo}" alt="" height="100px" />
                <a href="/admin/sponsor/deletelogo/{echo $sponsor->id}" id="delImg" class="btn btn3 btn_trash" title="Delete logo"></a>
            </span> 
            
            <span class="field nodisplay" id="uploadLogo" >
                <input type="file" name="logo" />
                {if isset($errors["logo"])}
                    <label class="error">{echo join("<br/>", $errors["logo"])}</label>
                {/if}
            </span>
            {/if}{else}
            <span class="field" id="uploadLogo">
                <input type="file" name="logo" />
                {if isset($errors["logo"])}
                    <label class="error">{echo join("<br/>", $errors["logo"])}</label>
                {/if}
            </span> 
            {/else}
        </p>
        <p>
            <label>Webpage*</label>
            <span class="field">
                <input required type="text" name="web" class="longinput" value="{echo $sponsor->web}"/>
                {if isset($errors["web"])}
                    <label class="error">{echo join("<br/>", $errors["web"])}</label>
                {/if}
            </span>
        </p>
       
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $sponsor->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>

        <p class="stdformbutton">
            <input name="submitEditSponsor" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
<br class="clear-all" />