<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Sponsor</a></li>
    <li><a href="/admin/sponsor/add/">Add Sponsor</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="image"><span>Sponsor List</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <td class="head0">Logo</td>
                <td class="head1">Title</td>
                <td class="head0">Web</td>
                <td class="head1">Created</td>
                <td class="head0">Status</td>
                <td class="head1">&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            {if !empty($sponsors)}
                {foreach $sponsor in $sponsors}
                    <tr>
                        <td class="center">
                            <a href="{echo $sponsor->getLogo()}" class="view">
                                <img src="{echo $sponsor->getLogo()}" alt="{echo $sponsor->getTitle()}" height="50px" />
                            </a>
                        </td>
                        <td>{echo $sponsor->getTitle()}</td>
                        <td>
                            <a href="{echo $sponsor->getWeb()}" target="_blank">{echo $sponsor->getWeb()}</a>
                        </td>
                        <td>{echo $sponsor->getCreated()}</td>
                        <td>
                            {if ($sponsor->active)}<span class="labelProduct labelProductGreen">Active</span>{/if}
                        </td>
                        <td>
                            <a href="/admin/sponsor/edit/{echo $sponsor->getId()}" class="btn btn3 btn_pencil" title="Edit"></a>
                            <a href="/admin/sponsor/delete/{echo $sponsor->getId()}" class="btn btn3 btn_trash ajaxBtn" title="Delete"></a>
                        </td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>