{if $news}

<article class="grid_12">
    <h1>{echo $news->title}</h1>
    <div class="newsDetail">
        <p>
            <span class="meta">Autor: {echo $news->author}</span>
            <span class="meta">Vytvoreno: {echo date("d.m. Y H:i", strtotime($news->created))}</span>
        </p>
        <hr/>
        <p class="newsText">{echo nl2br($news->body)}</p>
        <br/>
        
        {if !empty($photos)}
        <ul class="inline-list">
            {foreach $photo in $photos}
            <li>
                <a href="{echo $photo->pathLarge}">
                    <img src="{echo $photo->pathSmall}" alt="{echo $photo->photoName}"/>
                </a>
            </li>
            {/foreach}
        </ul>
        {/if}
    </div>
</article>

{/if}