<div class="homepage"></div>
<section class="basic aligncenter">
    
    <header><h1>Kontakty</h1></header>
    <p>
        Vedoucí týmu a pokladník v jedné osobě:<br/>
        Kočí Kamil<br/>
        KamilKoci@seznam.cz<br/>
        telefon: 607 768 203<br/>
    </p>
    <p>
        Trenér a kápo v jedné osobě:<br/>
        Jelínek Tomáš<br/>
        telefon: 723 139 095<br/>
    </p>
</section>