<div class="homepage"></div>
<section class="basic aligncenter">
    
    <header><h1>Kontakty</h1></header>
    <p>
        Vedoucí týmu a pokladník v jedné osobě:<br/>
        <strong>Kočí Kamil</strong><br/>
        KamilKoci@seznam.cz<br/>
        Telefon: 607 768 203<br/>
    </p>
    <p>
        Trenér a kápo v jedné osobě:<br/>
        <strong>Jelínek Tomáš</strong><br/>
        Telefon: 723 139 095<br/>
    </p>
</section>