<div class="homepage"></div>
<section class="grid_12 basic ">
    <header><h1>Novinky</h1></header>
    {if !empty($news)}
    {foreach $_news in $news}
    <div class="grid_6">
        <h2>{echo $_news->title}</h2><br/>
        <p class="newsText">{echo html_entity_decode($_news->shortBody)}</p>
        <p class="fs10">
            <span>Autor: {echo $_news->author}</span>
            <span>Vytvořeno: {echo date("d.m. Y H:i", strtotime($_news->created))}</span>
        </p>
    </div>
    {/foreach}
    {/if} 
</section>

<div class="clear"></div>

<section class="grid_12 indexNextMatch basic">
    <header><h1>Příští zápasy</h1></header>
    {if !empty($nextMatchA)}
    <div class="grid_6">
        <h2>A</h2>
        <table>
            <tr>
                <td>Datum</td><td>Domací</td><td>Hosté</td><td>Hala</td>
            </tr>
            {foreach $match in $nextMatchA}
            <tr>
                <td>{echo date("d.m. Y", strtotime($match->startDate))." ".$match->startTime}</td>
                <td>{echo $match->home}</td>
                <td>{echo $match->away}</td>
                <td>{echo $match->hall}</td>
            </tr>
            {/foreach}
        </table>
    </div>
    <div class="grid_6">
        <h2>B</h2>
        <table>
            <tr>
                <td>Datum</td><td>Domací</td><td>Hosté</td><td>Hala</td>
            </tr>
            {foreach $match in $nextMatchB}
            <tr>
                <td>{echo date("d.m. Y", strtotime($match->startDate))." ".$match->startTime}</td>
                <td>{echo $match->home}</td>
                <td>{echo $match->away}</td>
                <td>{echo $match->hall}</td>
            </tr>
            {/foreach}
        </table>
    </div>
    {/if} 
</section>

<div class="clear"></div>

<section class="grid_12 basic">
    <header><h1>Poslední zápasy</h1></header>
    {if !empty($lastMatchA)}
    {foreach $match in $lastMatchA}
    <div class="ribbon-wrapper lastmatch grid_5">
        {if (strtoupper(substr($match->home,0,14)) == "FBK VŠSK PEDF") && ($match->scoreHome > $match->scoreAway)}
        <div class="ribbon-wrapper-green"><div class="ribbon-green-left">Výhra</div></div>
        {/if}
        {elseif (strtoupper(substr($match->away,0,14)) == "FBK VŠSK PEDF") && ($match->scoreAway > $match->scoreHome)}
        <div class="ribbon-wrapper-green"><div class="ribbon-green-left">Výhra</div></div>
        {/elseif}
        {elseif (strtoupper(substr($match->home,0,14)) == "FBK VŠSK PEDF") && ($match->scoreHome < $match->scoreAway)}
        <div class="ribbon-wrapper-green"><div class="ribbon-red-left">Prohra</div></div>
        {/elseif}
        {elseif (strtoupper(substr($match->away,0,14)) == "FBK VŠSK PEDF") && ($match->scoreAway < $match->scoreHome)}
        <div class="ribbon-wrapper-green"><div class="ribbon-red-left">Prohra</div></div>
        {/elseif}
        {else}
        <div class="ribbon-wrapper-green"><div class="ribbon-orange-left">Remíza</div></div>
        {/else}

        <p class="lastmatch-left">
            Datum: {echo date("d.m. Y", strtotime($match->startDate))}<br/><br/>
            {echo $match->home} <span class="lastmatch-result">{echo $match->scoreHome}</span>
        </p>
        <p class="lastmatch-right">
            Hala: {echo $match->hall} <br/><br/>
            <span class="lastmatch-result">{echo $match->scoreAway}</span> {echo $match->away}
        </p>
    </div>
    {/foreach}
    {/if}{else}
    Žádné výsledky
    {/else}

    {if !empty($lastMatchB)}
    {foreach $match in $lastMatchB}
    <div class="ribbon-wrapper lastmatch grid_5">
        {if (strtoupper(substr($match->home,0,14)) == "FBK VŠSK PEDF") && ($match->scoreHome > $match->scoreAway)}
        <div class="ribbon-wrapper-green"><div class="ribbon-green-left">Výhra</div></div>
        {/if}
        {elseif (strtoupper(substr($match->away,0,14)) == "FBK VŠSK PEDF") && ($match->scoreAway > $match->scoreHome)}
        <div class="ribbon-wrapper-green"><div class="ribbon-green-left">Výhra</div></div>
        {/elseif}
        {elseif (strtoupper(substr($match->home,0,14)) == "FBK VŠSK PEDF") && ($match->scoreHome < $match->scoreAway)}
        <div class="ribbon-wrapper-green"><div class="ribbon-red-left">Prohra</div></div>
        {/elseif}
        {elseif (strtoupper(substr($match->away,0,14)) == "FBK VŠSK PEDF") && ($match->scoreAway < $match->scoreHome)}
        <div class="ribbon-wrapper-green"><div class="ribbon-red-left">Prohra</div></div>
        {/elseif}
        {else}
        <div class="ribbon-wrapper-green"><div class="ribbon-orange-left">Remíza</div></div>
        {/else}

        <p class="lastmatch-left">
            Datum: {echo date("d.m. Y", strtotime($match->startDate))}<br/><br/>
            {echo $match->home} <span class="lastmatch-result">{echo $match->scoreHome}</span>
        </p>
        <p class="lastmatch-right">
            Hala: {echo $match->hall} <br/><br/>
            <span class="lastmatch-result">{echo $match->scoreAway}</span> {echo $match->away}
        </p>
    </div>
    {/foreach}
    {/if}{else}
    Žádné výsledky
    {/else}
</section>

<div class="clear"></div>

<section class="grid_12 basic">
    <header><h1>Sponzoři</h1></header>
    {if !empty($sponsors)}
    <ul class="inline-list">
        {foreach $sponsor in $sponsors}
        <li>
            <a href="{echo $sponsor->web}" target=_blank>
                <img src="{echo $sponsor->logo}" alt="" />
            </a>
        </li>
        {/foreach}
    </ul>
    {/if}
</section>

<div class="clear"></div>