<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="cs" />
        {if $env == "live"}<meta http-equiv="CACHE-CONTROL" content="public, max-age=10800">{/if}
        {else}<meta http-equiv="CACHE-CONTROL" content="no-store">{/else}

        <meta name="viewport" content="width=device-width, maximum-scale=2.0, minimum-scale=1.0, initial-scale=1.0" />
        <meta name="language" content="czech" />
        <meta name="description" content="{echo $metadescription}" />
        <meta name="revisit-after" content="4 Days" />
        <meta name="distribution" content="global"/>
        <meta name="robots" content="{echo $metarobots}">

        <meta property="og:url" content="{echo $metaogurl}" />
        <meta property="og:title" content="{echo $metatitle}" />
        <meta property="og:description" content="{echo $metadescription}" />
        <meta property="og:type" content="{echo $metaogtype}" />
        <meta property="og:site_name" content="{echo $metaogsitename}" />

        <link href="/public/css/plugins/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/plugins/grid.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/plugins/smoothness/jquery-ui-1.10.4.custom.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/custom/styles.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/plugins/slides.css" media="screen" rel="stylesheet" type="text/css" />

        <!--[if lt IE 9]><script type="text/javascript" src="/public/js/html5.js"></script><![endif]-->
        <script type="text/javascript" src="/public/js/plugins/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/jquery-ui-1.10.4.custom.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/jquery.slides.min.js"></script>

        <title>Pedak</title>
    </head>
    <body lang="cs">
        <aside>
            <header>
                <hgroup>
                    <h1><a href="/">Peďák</a></h1>
                    <h3>florbalový klub</h3>    
                </hgroup>

                {include menu.phtml}
            </header>

            <footer>
                <section class="odkazy aligncenter">
                    <h1>Odkazy:</h1>
                    <ul>
                        <li><a href="http://www.floorball.org/default.asp" target=_blank>IFF</a></li>
                        <li><a href="http://cfbu.cz" target=_blank>ČFBU</a></li>
                    </ul>
                </section>

                <section class="madeBy aligncenter">  
                    <h1 class="visuallyhidden">Made by</h1>
                    <span>
                        Florbal Peďák | Made by<br/> Tomáš Hodáň<br/>  Tomáš Sláma<br/>
                    </span>
                </section>
            </footer>
        </aside>    

        <div class="clear"></div>

        <div id="contentWrapper">
            <div class="content">
                {if !empty($warningMessage)}
                <section class="container_12">
                    <h1 class="visuallyhidden">Warning message</h1>
                    <div class="ad-notif-warn grid_12"><p>{echo $warningMessage}</p></div>
                </section>
                {/if}

                {if !empty($successMessage)}
                <section class="container_12">
                    <h1 class="visuallyhidden">Success message</h1>
                    <div class="ad-notif-success grid_12"><p>{echo $successMessage}</p></div>
                </section>
                {/if}

                {if !empty($errorMessage)}
                <section class="container_12">
                    <h1 class="visuallyhidden">Error message</h1>
                    <div class="ad-notif-error grid_12"><p>{echo $errorMessage}</p></div>
                </section>
                {/if}

                <div class="container_12">
                    {yield action}
                </div>
            </div>
        </div>

        <div class="clear"></div>



        <div id="dialog"></div>

        <script type="text/javascript" src="/public/js/custom/global.js"></script>

    </body>
</html>
