<section class="grid_12 basic">
    <header><h1>Rozpis zápasů A</h1></header>
    <table>
        <tr>
            <td>Datum</td><td>Domácí</td><td>Hosté</td>
            <td>Hala</td><td>Výsledek</td>
            {if $isMember}<td>Detail</td>{/if}
        </tr>

        {foreach $match in $matchesA}
        <tr>
            <td>{echo date("d. m. Y", strtotime($match->startDate))." ".$match->startTime}</td>
            <td>{echo $match->home}</td>
            <td>{echo $match->away}</td>
            <td>{echo $match->hall}</td>

            {if $match->scoreHome != -1}
            <td>{echo $match->scoreHome} - {echo $match->scoreAway}</td>
            {/if}{else}
            <td>Neodehráno</td>
            {/else}
            {if ($isMember)}
            <td><a href="/zapasy/r/{echo $match->id}">Detail</a></td>
            {/if}
        </tr>
        {/foreach}
    </table>
</section>

<section class="grid_12 basic">
    <header><h1>Rozpis zápasů B</h1></header>
    <table>
        <tr>
            <td>Datum</td><td>Domácí</td><td>Hosté</td>
            <td>Hala</td><td>Výsledek</td>
            {if $isMember}<td>Detail</td>{/if}
        </tr>

        {foreach $match in $matchesB}
        <tr>
            <td>{echo date("d. m. Y", strtotime($match->startDate))." ".$match->startTime}</td>
            <td>{echo $match->home}</td>
            <td>{echo $match->away}</td>
            <td>{echo $match->hall}</td>

            {if $match->scoreHome != -1}
            <td>{echo $match->scoreHome} - {echo $match->scoreAway}</td>
            {/if}{else}
            <td>Neodehráno</td>
            {/else}
            {if ($isMember)}
            <td><a href="/zapasy/r/{echo $match->id}">Detail</a></td>
            {/if}
        </tr>
        {/foreach}
    </table>
</section>